import "./globals.css";
import Navigation from "@/components/navigation";
import Detail from "@/components/detail";
import AuthProvider from "@/components/AuthProvider";

export const metadata = {
  title: "잔디농장",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen">
        <div className="flex flex-col h-screen">
          <AuthProvider>
            <Navigation />
            {children}
          </AuthProvider>
        </div>
      </body>
    </html>
  );
}
